Feature/first version
wirenboard/wb-zigbee2mqtt pull request #1
Opened 2020-09-17 09:58 UTC by munrexio

2020-09-17 10:53 UTC, evgeny-boger requested changes

2020-09-17 10:53 UTC, evgeny-boger commented on debian/control
> +Maintainer: --
себя впиши пожалуйста с рабочей почтой

2020-09-17 10:53 UTC, evgeny-boger commented on debian/control
> +Depends: ${misc:Depends}, wb-rules (>= 2.6.0)
это правильная версия? Оно в 2.6.0 из стабильного репозитория уже работает?

2020-09-17 10:53 UTC, evgeny-boger commented on debian/control
> +Breaks:
убрать

2020-09-17 10:53 UTC, evgeny-boger commented on debian/wb-zigbee2mqtt.postinst
> +service wb-rules restart
по-моему не нужно - оно же само файлы обнаруживает
к тому же, если ты делаешь непустой postinst, то надо туда какой-то макрос вставлять, чтобы туда стандартное содержание postinst вставилось

2020-09-18 11:18 UTC, munrexio commented on debian/control
> +Depends: ${misc:Depends}, wb-rules (>= 2.6.0)
Версия правильная, в стабильном пока нет, в экспериментал лежит

2020-09-30 21:40 UTC, merged