Fix nested json parsing
wirenboard/wb-zigbee2mqtt pull request #11
Opened 2024-01-09 15:09 UTC by ekateluv

https://wirenboard.bitrix24.ru/company/personal/user/216/tasks/task/view/52514/?any=user%2F136%2Ftasks%2Ftask%2Fview%2F52514%2F
Раньше все поля просматривались вглубину, поэтому поле state в поле update переписывало поле с таким же именем уровнем выше. Сделала проход только по корневым полям объекта, все вложенные объекты переводятся в строку.

2024-01-10 13:45 UTC, KraPete commented on wb-zigbee2mqtt.js
> +        if (key in controlsTypes) {
Может, эти проверки вынести в функцию, которая возвратит значение для `dev[deviceName][key]`?

2024-01-11 11:10 UTC, ekateluv commented on wb-zigbee2mqtt.js
> +        if (key in controlsTypes) {
готово

2024-01-11 11:25 UTC, KraPete requested changes

2024-01-11 11:25 UTC, KraPete commented on wb-zigbee2mqtt.js
> +  } else {
Можно кучу `else` и `if` не делать. Уже же есть `return`

2024-01-11 11:25 UTC, KraPete commented on wb-zigbee2mqtt.js
> +function getContolValue(contolName, controlValue, controlsTypes) {
conrolsTypes же глобальная, можно не передавать

2024-01-11 11:27 UTC, ekateluv commented on wb-zigbee2mqtt.js
> +function getContolValue(contolName, controlValue, controlsTypes) {
Хм, можно, но мне чисто субьективно не нравится делать зависимости от глобальной переменной в нескольких функциях

2024-01-11 11:34 UTC, ekateluv commented on wb-zigbee2mqtt.js
> +  } else {
исправлено

2024-01-11 11:39 UTC, KraPete approved these changes
У меня нет возможности поверить на реальном железе

2024-01-17 10:23 UTC, merged